name: reactome_pathwaymatcher
owner: galaxyp
description: Reactome Pathway Matcher
homepage_url: https://github.com/LuisFranciscoHS/PathwayMatcher
long_description:
  PathwayMatcher is a free, open-source software to search for pathways related to a list of proteins in Reactome.

  https://github.com/LuisFranciscoHS/PathwayMatcher
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/pathwaymatcher
type: unrestricted
categories:
  - Proteomics
