categories:
- Proteomics
description: exports tabular files from imzML files
long_description: |
  exports tabular files with intensities, m/z features and spectra information from imzML files
name: msi_imzml_exporter
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/msi_imzml_exporter
homepage_url: http://cardinalmsi.org/
type: unrestricted
