categories:
  - Proteomics
description: MSstats tool for analyzing mass spectrometry proteomic datasets
long_description: |
    MSstats is an open-source R-based package for statistical relative quantification of peptides and proteins in mass spectrometry-based proteomic experiments.
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/msstats
homepage_url: https://github.com/MeenaChoi/MSstats
type: unrestricted
