categories:
- Proteomics
description: MALDIquant provides a complete analysis pipeline for MALDI-TOF and other 2D mass spectrometry data.
long_description: |
    MALDIquant is free and open source software for the R environment Distinctive features include baseline subtraction methods such as TopHat or SNIP, peak alignment using warping functions, handling of replicated measurements as well as allowing spectra with different resolutions. 
name: MALDIquant
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/MALDIquant
homepage_url: http://strimmerlab.org/software/maldiquant/
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for the MALDIquant suite tool: {{ tool_name }}"
suite:
  name: "suite_maldiquant"
  description: MALDIquant Suite for 2D mass spectrometry data analyses
  long_description:
    MALDIquant is free and open source software for the R environment Distinctive features include baseline subtraction methods such as TopHat or SNIP, peak alignment using warping functions, handling of replicated measurements as well as allowing spectra with different resolutions. 
