categories: [Proteomics]
description: Correlation between protein and transcript abundance
long_description: |
    This tool evaluates the correlation between protein and transcript abundances and presents result in HTML format.
name: quantp
owner: galaxyp
