categories:
  - Proteomics
  - Metabolomics
description: Statistical and computational tools for analyzing mass spectrometry imaging datasets
long_description: |
    Cardinal is an R package that implements statistical and computational tools for analyzing mass spectrometry imaging datasets.
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/cardinal
homepage_url: http://cardinalmsi.org
type: unrestricted
auto_tool_repositories:
    name_template: "{{ tool_id }}"
    description_template: "Cardinal (mass spectrometry imaging) suite: {{ tool_name }}"
suite:
    name: "suite_cardinal"
    description: Statistical and computational tools for analyzing mass spectrometry imaging datasets
    long_description:
        Cardinal is an R package that implements statistical and computational tools for analyzing mass spectrometry imaging datasets.
